id: c4ddfefbc6c546888ee2d61977410bfc
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_431-The_Tantra_of_Candamaharosana-v1
  language: en
  author: ''
  volume: {}
